/**
 * Writes src/generated/flags.ts: a square SVG flag (as a data URI) for the
 * region of every locale in project.inlang/settings.json, from
 * country-flag-icons. Only configured locales' flags are included, so adding
 * a locale adds its flag without shipping the whole set. Runs before
 * `build`/`dev`; the output is gitignored.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";

const ROOT = path.join(import.meta.dirname, "..");
const OUTPUT_DIR = path.join(ROOT, "src/generated");
const FLAGS_DIR = path.join(
  path.dirname(createRequire(import.meta.url).resolve("country-flag-icons/package.json")),
  "1x1",
);

const { locales } = JSON.parse(
  await readFile(path.join(ROOT, "project.inlang/settings.json"), "utf8"),
);
const regions = [
  ...new Set(locales.map((locale) => new Intl.Locale(locale).maximize().region)),
].filter(Boolean);

const flags = {};
for (const region of regions.sort((a, b) => a.localeCompare(b))) {
  const svg = await readFile(path.join(FLAGS_DIR, `${region}.svg`), "utf8");
  flags[region] = `data:image/svg+xml,${encodeURIComponent(svg.trim())}`;
}

await mkdir(OUTPUT_DIR, { recursive: true });
await writeFile(path.join(OUTPUT_DIR, ".gitignore"), "*\n");
await writeFile(
  path.join(OUTPUT_DIR, "flags.ts"),
  `// Generated by scripts/generate-flags.mjs. Do not edit.\n` +
    `export const flags: Record<string, string> = ${JSON.stringify(flags, null, 2)};\n`,
);
