import { describe, expect, it } from "vitest";

import colors, { gradientStops, rampScaleStops } from "./colors";
import darkColors from "./darkColors";
import { contrastRatio } from "./gradients";

// The eleven semantic-palette hues; `gray` is included, per the
// spec's own scale table, alongside the ten colour hues.
const HUES = [
  "gray",
  "red",
  "orange",
  "yellow",
  "green",
  "teal",
  "cyan",
  "blue",
  "indigo",
  "purple",
  "pink",
] as const;

const BLACK: [number, number, number] = [0, 0, 0];
const WHITE: [number, number, number] = [255, 255, 255];

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [
    Number.parseInt(h.slice(0, 2), 16),
    Number.parseInt(h.slice(2, 4), 16),
    Number.parseInt(h.slice(4, 6), 16),
  ];
}

// The stop contract's contrast rules.
describe("semantic palette stop contract", () => {
  it.each(HUES)("%s.500 clears 4.5:1 against black (it's a light fill under black text)", (hue) => {
    expect(contrastRatio(hexToRgb(colors[hue][500]), BLACK)).toBeGreaterThanOrEqual(4.5);
  });

  it.each(HUES)("%s.600 clears 4.5:1 against white (it's a dark fill under white text)", (hue) => {
    expect(contrastRatio(hexToRgb(colors[hue][600]), WHITE)).toBeGreaterThanOrEqual(4.5);
  });

  it.each(HUES)("%s.700 clears 4.5:1 against white (it's a dark fill under white text)", (hue) => {
    expect(contrastRatio(hexToRgb(colors[hue][700]), WHITE)).toBeGreaterThanOrEqual(4.5);
  });

  it.each(HUES)("%s.900 clears 4.5:1 against its own %s.100 (near-black text on a wash)", (hue) => {
    expect(
      contrastRatio(hexToRgb(colors[hue][900]), hexToRgb(colors[hue][100])),
    ).toBeGreaterThanOrEqual(4.5);
  });
});

describe("gray.1100 removal (step 5 of the palette migration)", () => {
  it("is gone from the palette entirely", () => {
    expect(colors.gray[1100]).toBeUndefined();
  });

  it("dark-mode background/foreground still hardcodes the old gray.1100 value", () => {
    expect(colors.modes.dark.bg).toBe("#292929");
    expect(colors.modes.dark.background).toBe("#292929");
  });
});

// The six brand ramps' 100-900 scale (`rampScaleStops`) — same stop
// contract as the semantic palette above, since it's generated by the same
// methodology (`scripts/generate-ramp-scale.mjs`). `600`/`800` are pinned to
// the ramp's `mid`/`deep` gradient stops (unchanged from before this scale
// existed), so every existing `colorPalette.deep`/`.mid` consumer renames to
// `.800`/`.600` with no visual change.
const RAMP_NAMES = Object.keys(gradientStops) as Array<keyof typeof gradientStops>;

describe("ramp scale stop contract", () => {
  it.each(RAMP_NAMES)("%s.600 is pinned to the ramp's 62% (mid) gradient stop", (name) => {
    expect(rampScaleStops[name][600]).toBe(gradientStops[name][3]);
  });

  it.each(RAMP_NAMES)("%s.800 is pinned to the ramp's 40% (deep) gradient stop", (name) => {
    expect(rampScaleStops[name][800]).toBe(gradientStops[name][2]);
  });

  it.each(RAMP_NAMES)("%s.500 clears 4.5:1 against black (it's a light fill under black text)", (name) => {
    expect(contrastRatio(hexToRgb(rampScaleStops[name][500]), BLACK)).toBeGreaterThanOrEqual(4.5);
  });

  it.each(RAMP_NAMES)(
    "%s.600 clears 4.5:1 against white (it's a dark fill under white text)",
    (name) => {
      expect(contrastRatio(hexToRgb(rampScaleStops[name][600]), WHITE)).toBeGreaterThanOrEqual(4.5);
    },
  );

  it.each(RAMP_NAMES)("%s.700 clears 4.5:1 against white", (name) => {
    expect(contrastRatio(hexToRgb(rampScaleStops[name][700]), WHITE)).toBeGreaterThanOrEqual(4.5);
  });

  it.each(RAMP_NAMES)("%s.900 clears 4.5:1 against its own %s.100 (near-black text on a wash)", (name) => {
    expect(
      contrastRatio(hexToRgb(rampScaleStops[name][900]), hexToRgb(rampScaleStops[name][100])),
    ).toBeGreaterThanOrEqual(4.5);
  });

  // 100/200/300/400/700 relate to the page background and must actually flip
  // between modes (that's the whole point — a divider/tick using one of
  // these needs a *different* hex in dark mode to stay visible); 500/600/800/
  // 900 are fills that invert role instead — a light fill under black text
  // becomes a dark fill under white text, and vice versa — so their dark
  // value must also differ from light.
  it.each(RAMP_NAMES)("%s's bg-anchored stops differ between light and dark", (name) => {
    for (const stop of [100, 200, 300, 400, 700]) {
      expect(darkColors[name][stop as 100]).not.toBe(rampScaleStops[name][stop]);
    }
  });

  it.each(RAMP_NAMES)("%s's fill stops invert between light and dark modes", (name) => {
    for (const stop of [500, 600, 800, 900]) {
      expect(darkColors[name][stop as 500]).not.toBe(rampScaleStops[name][stop]);
    }
  });

  it.each(RAMP_NAMES)("%s.500's dark counterpart clears 4.5:1 against white (light fill under black text becomes a dark fill under white text)", (name) => {
    expect(contrastRatio(hexToRgb(darkColors[name][500]), WHITE)).toBeGreaterThanOrEqual(4.5);
  });

  it.each(RAMP_NAMES)(
    "%s.600's dark counterpart clears 4.5:1 against black (dark fill under white text becomes a light fill under black text)",
    (name) => {
      expect(contrastRatio(hexToRgb(darkColors[name][600]), BLACK)).toBeGreaterThanOrEqual(4.5);
    },
  );

  it.each(RAMP_NAMES)("%s.800's dark counterpart clears 4.5:1 against black", (name) => {
    expect(contrastRatio(hexToRgb(darkColors[name][800]), BLACK)).toBeGreaterThanOrEqual(4.5);
  });
});

describe("brand alias", () => {
  it("is the Hibiscus accent, not red.600", () => {
    expect(colors.brand).toBe("#A83A5C");
    expect(colors.brand).not.toBe(colors.red[600]);
  });
});
