// Alpha color scales (previously from @chakra-ui/theme)
const blackAlpha: Record<string, string> = {
  50: "rgba(0, 0, 0, 0.04)",
  100: "rgba(0, 0, 0, 0.06)",
  200: "rgba(0, 0, 0, 0.08)",
  300: "rgba(0, 0, 0, 0.16)",
  400: "rgba(0, 0, 0, 0.24)",
  500: "rgba(0, 0, 0, 0.36)",
  600: "rgba(0, 0, 0, 0.48)",
  700: "rgba(0, 0, 0, 0.64)",
  800: "rgba(0, 0, 0, 0.80)",
  900: "rgba(0, 0, 0, 0.92)",
};

const whiteAlpha: Record<string, string> = {
  50: "rgba(255, 255, 255, 0.04)",
  100: "rgba(255, 255, 255, 0.06)",
  200: "rgba(255, 255, 255, 0.08)",
  300: "rgba(255, 255, 255, 0.16)",
  400: "rgba(255, 255, 255, 0.24)",
  500: "rgba(255, 255, 255, 0.36)",
  600: "rgba(255, 255, 255, 0.48)",
  700: "rgba(255, 255, 255, 0.64)",
  800: "rgba(255, 255, 255, 0.80)",
  900: "rgba(255, 255, 255, 0.92)",
};

// Only ever consumed at 180deg (Organism/Header's mobile-nav overlay), so this
// is a plain two-color helper rather than the old all-angles `linearGrads`.
const grad180 = (from: string, to: string) => `linear-gradient(180deg, ${from} 0%, ${to} 100%)`;

// ---------------------------------------------------------------------------
// The six brand gradients. Each ramp is six stops between a
// shared near-black `#120510` and a shared sand `#F7DEC9` — the shared
// endpoints are what make them read as one family.
//
// Stop roles: 62% is the ramp's midpoint and doubles as the solid accent
// colour (focus rings, tab markers, checked states); 40% is the deep. 82%
// and 100% are decorative-only — white text never sits over them (see
// `capRamp` in `./gradients.ts`).
// ---------------------------------------------------------------------------
export const gradientStops = {
  hibiscus: ["#120510", "#38102A", "#701C46", "#A83A5C", "#D97C56", "#F7DEC9"],
  hotsauce: ["#120510", "#3E1206", "#7E2608", "#BC4A1A", "#E28C3C", "#F7DEC9"],
  chilioil: ["#120510", "#380A10", "#6E1620", "#A82A2E", "#D9603E", "#F7DEC9"],
  blackberry: ["#120510", "#2C1638", "#5E2A52", "#9B4A4E", "#D08A4A", "#F7DEC9"],
  figjam: ["#120510", "#241242", "#4A2270", "#8A3A78", "#C87264", "#F7DEC9"],
  marmalade: ["#120510", "#33260A", "#6B4E10", "#956F0A", "#DCB43C", "#F7DEC9"],
} as const;

export const STOP_POSITIONS = [0, 20, 40, 62, 82, 100] as const;

// ---------------------------------------------------------------------------
// Each ramp's dark-mode "field" stops — generated by
// `scripts/generate-dark-gradient-stops.mjs` (an OKLCH lift, not hand-picked).
// Only the 0/20/40/62% run gets a counterpart: that's the only part of a ramp
// that ever carries a contrast requirement (white text, or the ramp used as a
// foreground accent) — 82%/100% stay the shared decorative sand tail in both
// modes, per this file's own stop-role comment above.
//
// 0% is the shared near-black anchor (`#120510`) and is pinned, copied
// verbatim rather than recomputed — moving it would break the "shared
// anchor" read across all six ramps. Every other stop keeps its own
// light-mode hue exactly and has its lightness scaled up by a single
// per-ramp factor so the 62% stop's L lands at 0.62 (bright enough to read
// as a foreground accent against the dark ground, `colors.modes.dark.bg`,
// rather than the deep-fill role it plays in light mode), with chroma
// boosted alongside it — +0% at the anchor rising to +25% at the 62% stop
// (clamped to the sRGB gamut per stop, since a naive +25% overshoots it for
// hotsauce and marmalade's hues at this lightness). The result: each ramp's
// 62% stop holds ~4.5-5:1 against the dark ground, in the same ballpark as
// light mode's own white-on-62%-stop contrast (see `accentOnWhite` in
// `gradients.test.ts`) rather than the near-black anchor's near-illegible
// contrast against it.
//
// Re-run the script and paste its output here whenever a ramp's light-mode
// `gradientStops` above change.
// ---------------------------------------------------------------------------
export const darkGradientStops: Record<
  keyof typeof gradientStops,
  readonly [string, string, string, string]
> = {
  hibiscus: ["#120510", "#481B38", "#8F2A5C", "#DB4A78"],
  hotsauce: ["#120510", "#48180A", "#952B03", "#E14F00"],
  chilioil: ["#120510", "#4C191E", "#952B34", "#E74045"],
  blackberry: ["#120510", "#3A2248", "#7A3B6B", "#CB6066"],
  figjam: ["#120510", "#362359", "#693A99", "#C258AA"],
  marmalade: ["#120510", "#3B2C0E", "#7B5908", "#AA7E00"],
};

// ---------------------------------------------------------------------------
// Each ramp's mode-aware 100-900 swatch scale — generated by
// `scripts/generate-ramp-scale.mjs` (an OKLCH search, same methodology as
// `gray`/`red`'s scale in `darkColors.ts`), not hand-picked. `600`/`800`'s
// LIGHT-mode value is pinned to the ramp's own `deep`/`mid` gradient stops
// above (40%/62%) — every existing consumer of the old flat `colorPalette.
// deep`/`.mid` names renames to `.800`/`.600` with zero visual change in
// light mode. Every stop, including `600`/`800`, is genuinely mode-aware
// (see `darkColors.ts`) — none of the nine stops repeat their light-mode hex
// in dark mode, so e.g. `colorPalette.300` (or `.600`) is safe to use
// anywhere it needs to read correctly in both modes, the same guarantee
// `gray.300` already provides.
//
// `50` is an even paler/lower-chroma wash for background tints — `.100`
// turned out too saturated for that role once it replaced a near-white alpha
// blend. Every ramp carries the full 50-900 range so a ramp is usable in
// exactly the same ways as a semantic hue (`colorPalette.50` under
// `colorPalette="figjam"` resolves just like it does under `"blue"`).
//
// Re-run the script and paste its output here whenever a ramp's `deep`/`mid`
// stop above changes.
// ---------------------------------------------------------------------------
export const rampScaleStops: Record<keyof typeof gradientStops, Record<number, string>> = {
  hibiscus: {
    50: "#fcf7f8",
    100: "#ffe6eb",
    200: "#ffdce3",
    300: "#fed2db",
    400: "#ffacbe",
    500: "#fb84a3",
    600: "#A83A5C",
    700: "#80214c",
    800: "#701C46",
    900: "#420e28",
  },
  hotsauce: {
    50: "#fcf7f6",
    100: "#fff2ee",
    200: "#fff1ec",
    300: "#ffe7df",
    400: "#fec6b2",
    500: "#fea180",
    600: "#BC4A1A",
    700: "#953008",
    800: "#7E2608",
    900: "#531a09",
  },
  chilioil: {
    50: "#f9f4f3",
    100: "#f9ddda",
    200: "#f9d3cf",
    300: "#f9c9c5",
    400: "#fba39d",
    500: "#f97b76",
    600: "#A82A2E",
    700: "#7f1120",
    800: "#6E1620",
    900: "#3f040b",
  },
  blackberry: {
    50: "#fbf7f7",
    100: "#fbe7e7",
    200: "#fadede",
    300: "#f8d5d5",
    400: "#f3b4b4",
    500: "#eb9294",
    600: "#9B4A4E",
    700: "#713153",
    800: "#5E2A52",
    900: "#37172f",
  },
  figjam: {
    50: "#f4f1f3",
    100: "#eedbe8",
    200: "#ecd2e4",
    300: "#e9c8df",
    400: "#e2a5d1",
    500: "#d882c2",
    600: "#8A3A78",
    700: "#572971",
    800: "#4A2270",
    900: "#241039",
  },
  marmalade: {
    50: "#faf8f5",
    100: "#fcf4e4",
    200: "#fff4df",
    300: "#fdeed2",
    400: "#f0d49d",
    500: "#e2b965",
    600: "#956F0A",
    700: "#735305",
    800: "#6B4E10",
    900: "#422d01",
  },
};

export type GradientName = keyof typeof gradientStops;

// Per-section primary button fills — each ramp compressed as
// far as it can travel while still holding white text at AA, plus a
// hand-tuned lightened tail. These are fixed values from the approved build,
// not derived.
export const gradientButtonStops = {
  hibiscus: ["#38102A", "#A83A5C", "#BC545A"],
  hotsauce: ["#3E1206", "#BC4A1A", "#CE5E22"],
  chilioil: ["#380A10", "#A82A2E", "#B93A34"],
  blackberry: ["#2C1638", "#9B4A4E", "#AD5A51"],
  figjam: ["#241242", "#8A3A78", "#9D4A79"],
  marmalade: ["#33260A", "#8C6C15", "#9C7A18"],
} as const;

export const GRADIENT_BUTTON_POSITIONS = [0, 62, 100] as const;

// Badge `gradient` variant fills — its own hand-tuned
// two-color set, not the general deep/mid stops. Marmalade has no separate
// hand-tuned value yet — falls back to its own deep/mid stops, which (now
// that marmalade's mid stop clears 4.5:1 against white, see colors.test.ts)
// still resolves to a contract-clearing pair for every ramp.
export const badgeGradientStops: Record<GradientName, readonly [string, string]> = {
  hibiscus: ["#6A1A43", "#A83A5C"],
  hotsauce: ["#77240A", "#BC4A1A"],
  blackberry: ["#59284E", "#9B4A4E"],
  figjam: ["#472170", "#8A3A78"],
  chilioil: ["#6B1620", "#A82A2E"],
  marmalade: [gradientStops.marmalade[2], gradientStops.marmalade[3]],
};

const colors: Record<string, any> = {
  blackAlpha,
  whiteAlpha,
  black: "#252222",
  white: "#ffffff",
  // ---------------------------------------------------------------------------
  // Semantic palette. Eleven scales at ten stops (the full Chakra-style
  // 50-900 scale), derived in OKLCH so lightness is perceptually even across
  // hues (chroma capped at 0.155, just under the gradients' own peak chroma
  // of 0.162, so these never out-saturate the brand).
  //
  // Only 100/300/500/600/700/900 were hand-verified against the contract
  // below (see colors.test.ts) when the scale was first built; 50/200/400/800
  // are computed the same way as every dark-mode counterpart in this file —
  // OKLCH interpolation, not hand-picked — by `scripts/generate-dark-
  // scale.mjs` (its light-stop pass): 200/400/800 sit at the OKLCH lightness
  // midpoint of their two neighbors (holding each hue's own chroma
  // interpolated the same way); 50 extrapolates past 100 on the same
  // lightness curve, at 100's chroma scaled down 30% (a paler, lower-chroma
  // wash, same idea as `rampScaleStops`' hibiscus.50).
  //
  // Stop contract: 500 is a light fill that takes BLACK text. 600 and 700
  // are dark fills that take WHITE text. 100 is a wash. 300 is a light
  // accent. 900 is near-black text on a 100 wash. 800 is treated as a fill
  // paired with WHITE text too (like 600), since it sits in the same "dark
  // half" of the scale as 600/900. 50/200/400 are additional wash/accent
  // stops (same bg-anchored role as 100/300) — not text-contrast fills; do
  // not put fixed-color text directly on them expecting AA contrast.
  //
  // Re-run `scripts/generate-dark-scale.mjs` (with no args) and paste its
  // light+dark output here and into `darkColors.ts` whenever a stop changes.
  // ---------------------------------------------------------------------------
  gray: {
    50: "#FCECE7",
    100: "#F7E5D8",
    200: "#F0DDD6",
    300: "#E7D7CF",
    400: "#CFBEB8",
    500: "#B8A7A1",
    600: "#6F5F5A",
    700: "#524440",
    800: "#3D302C",
    900: "#2A1E20",
  },
  red: {
    50: "#FEEBE8",
    100: "#FBE4D7",
    200: "#FDD7D2",
    300: "#FECEC5",
    400: "#FFA89D",
    500: "#FD8074",
    600: "#AA342E",
    700: "#841817",
    800: "#620F0E",
    900: "#41060C",
  },
  orange: {
    50: "#FEECE2",
    100: "#FBE4D4",
    200: "#FDD9C5",
    300: "#FED0B4",
    400: "#FBAE7F",
    500: "#F68B43",
    600: "#9A4900",
    700: "#713400",
    800: "#522503",
    900: "#371707",
  },
  yellow: {
    50: "#F8F0D5",
    100: "#FBE6C2",
    200: "#F2E2A4",
    300: "#F3D983",
    400: "#DDC155",
    500: "#C9A800",
    600: "#766200",
    700: "#564700",
    800: "#3E3305",
    900: "#2B1F07",
  },
  green: {
    50: "#E4F6E4",
    100: "#E6EDCC",
    200: "#C4EFC4",
    300: "#B3ECAC",
    400: "#8BD88D",
    500: "#65C46A",
    600: "#06791F",
    700: "#005813",
    800: "#093F10",
    900: "#07270D",
  },
  teal: {
    50: "#E2F5EE",
    100: "#E0EDD8",
    200: "#B5F1DB",
    300: "#91F0CC",
    400: "#5FDCB6",
    500: "#00C89D",
    600: "#00755A",
    700: "#005541",
    800: "#0A3D2F",
    900: "#072521",
  },
  cyan: {
    50: "#E8F2F3",
    100: "#E4EBE1",
    200: "#B4EEF4",
    300: "#7EEDF6",
    400: "#55D7E6",
    500: "#00C1D1",
    600: "#00717A",
    700: "#005259",
    800: "#053B40",
    900: "#07242C",
  },
  blue: {
    50: "#ECF0F5",
    100: "#EFE7E1",
    200: "#D5E3F3",
    300: "#C7DDF6",
    400: "#95C7FB",
    500: "#60B0FF",
    600: "#0065B0",
    700: "#004982",
    800: "#02355F",
    900: "#07203E",
  },
  indigo: {
    50: "#EEEFF7",
    100: "#F2E6E1",
    200: "#DDE0F5",
    300: "#D7D8F6",
    400: "#B4BDFC",
    500: "#97A1FF",
    600: "#5254B9",
    700: "#393992",
    800: "#29296C",
    900: "#1F1847",
  },
  purple: {
    50: "#F5EDF7",
    100: "#F9E3E1",
    200: "#F1D7F7",
    300: "#F5CAF6",
    400: "#E3AAF1",
    500: "#D588E7",
    600: "#883F99",
    700: "#682576",
    800: "#4C1957",
    900: "#340E3A",
  },
  pink: {
    50: "#FDEBEF",
    100: "#FBE3DA",
    200: "#FBD6E0",
    300: "#FECCD5",
    400: "#FBA5C0",
    500: "#F77DA7",
    600: "#A53260",
    700: "#7F1744",
    800: "#5E0D31",
    900: "#3F0523",
  },
};

// Hibiscus's accent-on-white — not the raw 62% stop, the
// contrast-walked value from `accentOnWhite`, which for Hibiscus happen to
// be the same since Hibiscus already clears 4.5:1 at its 62% stop.
colors.brand = gradientStops.hibiscus[3];
colors.success = {
  border: colors.green[100],
  bg: colors.green[500],
  text: colors.green[900],
};
colors.failure = {
  border: colors.red[100],
  bg: colors.red[500],
  text: colors.red[900],
};
colors.grad = {
  // Only ever consumed at 180deg (Header's mobile-nav overlay via the `Box`
  // `grad` prop), so this is a flat sm/lg pair rather than the old
  // all-angles table `linearGrads` used to produce.
  darken: {
    sm: grad180(blackAlpha[300], "rgba(0,0,0,0)"),
    lg: grad180(blackAlpha[700], "rgba(0,0,0,0)"),
  },
  lighten: {
    sm: grad180(whiteAlpha[300], "rgba(255, 255, 255, 0)"),
    lg: grad180(whiteAlpha[700], "rgba(255, 255, 255, 0)"),
  },
  // Skelly retuned to the new neutrals, 90deg (paired with
  // the component's own background-size/animation-duration retune).
  skelly: `linear-gradient(90deg, ${colors.gray[300]} 0, ${colors.gray[100]} 50%, ${colors.gray[300]} 100%)`,
  darkSkelly: `linear-gradient(90deg, ${colors.gray[700]} 0, ${colors.gray[600]} 50%, ${colors.gray[700]} 100%)`,
};
colors.modes = {
  light: {
    color: colors.black,
    text: colors.black,
    textLight: "#717171",
    bg: colors.white,
    background: colors.white,
    primary: colors.brand,
    // gray.200 no longer exists in the new six-stop scale (100/300/500/600/700/900);
    // nearest stop by role (a visible-but-quiet light border) is gray.300.
    border: colors.gray[300],
    borderColor: colors.gray[300],
    placeholder: colors.gray[600],
  },
  dark: {
    color: whiteAlpha[900],
    text: whiteAlpha[900],
    textLight: "#717171",
    // gray.1100 is removed entirely (step 5 of the palette migration) — the dark-mode
    // page background is hardcoded here rather than being a palette stop.
    // Warm near-black derived from the #120510 brand anchor, sitting below the
    // ramp so it reads as ground rather than a step in it (Wash/gradient fix).
    bg: "#1E1119",
    background: "#1E1119",
    primary: colors.brand,
    border: whiteAlpha[300],
    borderColor: whiteAlpha[300],
    placeholder: whiteAlpha[400],
  },
};
colors.current = colors.modes.light;

export default colors;
