// Dark-mode counterparts for the eleven semantic hues' full ten-stop scale
// (`gray`, `red`, and the nine colour hues), generated by
// `scripts/generate-dark-scale.mjs` — an OKLCH search against target
// contrast ratios, not hand-picked or a mechanical light/dark inversion.
//
// Every stop differs from its light value. 50/100/200/300/400/700 relate to
// the page background (wash, light accent, on-wash/on-page text). 500/600/
// 800/900 are fills whose contrast requirement is against a fixed text
// color — rather than staying identical, each inverts its role for dark
// mode (a light fill built for black text becomes a dark fill built for
// white text, and vice versa), holding the same contrast ratio the light
// stop held against its own paired text (see the script's header comment
// for the full reasoning). Consumers that paired one of these fills with a
// fixed `trueWhite`/`trueBlack` label need that label switched to the
// self-inverting `white`/`black`, since the fill now flips right along with
// it.
//
// Re-run the script and paste its output here whenever a light-mode anchor
// stop (100/300/500/600/700/900) in `colors.ts` changes — the script
// re-derives 50/200/400/800 (light and dark) from the anchors itself, so
// `colors.ts`'s own 50/200/400/800 need re-pasting too at the same time.
const darkColors = {
  gray: {
    50: "#3b312e",
    100: "#41352c",
    200: "#463934",
    300: "#493e38",
    400: "#594d49",
    500: "#655854",
    600: "#ac9d98",
    700: "#daccc8",
    800: "#f2e3df",
    900: "#fff7f9",
  },
  red: {
    50: "#3c302e",
    100: "#43342b",
    200: "#4f3633",
    300: "#593833",
    400: "#7f3f38",
    500: "#a13f38",
    600: "#f2887c",
    700: "#ffc8bc",
    800: "#ffe3d8",
    900: "#ffe8e5",
  },
  orange: {
    50: "#3c302a",
    100: "#433429",
    200: "#4f3729",
    300: "#583925",
    400: "#7b421c",
    500: "#994600",
    600: "#dd9264",
    700: "#ffc5a0",
    800: "#ffe4c7",
    900: "#fff2e1",
  },
  yellow: {
    50: "#383220",
    100: "#43351b",
    200: "#463a04",
    300: "#503d00",
    400: "#624c00",
    500: "#715700",
    600: "#b09f5e",
    700: "#dbcd99",
    800: "#efe5bd",
    900: "#fffae1",
  },
  green: {
    50: "#293529",
    100: "#343822",
    200: "#224123",
    300: "#1c4718",
    400: "#18581f",
    500: "#0e651c",
    600: "#5dab60",
    700: "#98d799",
    800: "#bfeebf",
    900: "#e6ffe8",
  },
  teal: {
    50: "#283530",
    100: "#31392b",
    200: "#104133",
    300: "#004730",
    400: "#00573e",
    500: "#006344",
    600: "#5fa990",
    700: "#9bd6c0",
    800: "#c1ecdb",
    900: "#e6fffd",
  },
  cyan: {
    50: "#2d3435",
    100: "#343832",
    200: "#104044",
    300: "#00464d",
    400: "#005561",
    500: "#00616e",
    600: "#60a7af",
    700: "#9cd4db",
    800: "#c0ebf0",
    900: "#e5ffff",
  },
  blue: {
    50: "#303336",
    100: "#3b3632",
    200: "#333c47",
    300: "#324152",
    400: "#2b5177",
    500: "#175d99",
    600: "#62a4e8",
    700: "#9ed4ff",
    800: "#c1ecff",
    900: "#e3feff",
  },
  indigo: {
    50: "#323338",
    100: "#3d3532",
    200: "#393b49",
    300: "#3e3e53",
    400: "#484d7b",
    500: "#50569f",
    600: "#949df8",
    700: "#c4d0ff",
    800: "#dee9ff",
    900: "#f6f6ff",
  },
  purple: {
    50: "#363137",
    100: "#423433",
    200: "#48364c",
    300: "#553756",
    400: "#6c4277",
    500: "#834791",
    600: "#cf8fdf",
    700: "#ffc1ff",
    800: "#ffe3ff",
    900: "#ffebff",
  },
  pink: {
    50: "#3b3032",
    100: "#43342e",
    200: "#4e363d",
    300: "#59373e",
    400: "#7d3e54",
    500: "#9d3e62",
    600: "#ef86a8",
    700: "#ffc5e3",
    800: "#ffe0f9",
    900: "#ffe6fe",
  },
  // ---------------------------------------------------------------------------
  // The six brand ramps' 100-900 scales (see `colors.ts`'s `rampScaleStops`),
  // generated by `scripts/generate-ramp-scale.mjs`. `100`/`200`/`300`/`400`/
  // `700` relate to the page background and flip. `500`/`600`/`800`/`900` are
  // fills that invert role rather than staying identical: a light fill built
  // for black text becomes a dark fill built for white text (500), and a
  // dark fill built for white text becomes a light fill built for black text
  // (600, 800, 900) — `600`/`800` no longer match the (never-mode-aware) raw
  // `gradientStops` mid/deep hex in dark mode as a result; see the script's
  // header comment. `50` (hibiscus only, provisional) is a bg-anchored wash
  // like `100`/`200`/`300`/`400` — see `colors.ts`'s note.
  // ---------------------------------------------------------------------------
  hibiscus: {
    50: "#302d2d",
    100: "#413134",
    200: "#4a3339",
    300: "#53363d",
    400: "#783c4b",
    500: "#983c57",
    600: "#e7839c",
    700: "#febfd4",
    800: "#ffc6db",
    900: "#fff9fc",
  },
  hotsauce: {
    100: "#362e2b",
    200: "#372e2b",
    300: "#41322c",
    400: "#623b2d",
    500: "#823d24",
    600: "#db7753",
    700: "#ffa88d",
    800: "#ffbba7",
    900: "#ffece7",
  },
  chilioil: {
    100: "#483634",
    200: "#523936",
    300: "#5c3b39",
    400: "#83423f",
    500: "#a54240",
    600: "#fc8b85",
    700: "#ffd0ce",
    800: "#fed4d3",
    900: "#fff9f9",
  },
  blackberry: {
    100: "#3f3232",
    200: "#473535",
    300: "#4f3838",
    400: "#6e4242",
    500: "#8b474a",
    600: "#d78c8d",
    700: "#febcdb",
    800: "#fdc6ed",
    900: "#fffafd",
  },
  figjam: {
    100: "#453841",
    200: "#4d3b48",
    300: "#553f4f",
    400: "#754869",
    500: "#904c7f",
    600: "#e196cd",
    700: "#edd4ff",
    800: "#e9dafe",
    900: "#fdfaff",
  },
  marmalade: {
    100: "#342f24",
    200: "#352e20",
    300: "#3b311e",
    400: "#533f12",
    500: "#634800",
    600: "#a78641",
    700: "#cfb17a",
    800: "#cdb282",
    900: "#fee7c2",
  },
} as const;

export default darkColors;
