// Dark-mode counterparts for `gray`/`red`'s six-stop scale, generated by
// `scripts/generate-dark-scale.mjs` — an OKLCH search against target
// contrast ratios, not hand-picked or a mechanical light/dark inversion.
//
// Every stop differs from its light value. 100/300/700 relate to the page
// background (wash, light accent, on-wash/on-page text). 500/600/900 are
// fills whose contrast requirement is against a fixed text color — rather
// than staying identical, each inverts its role for dark mode (a light fill
// built for black text becomes a dark fill built for white text, and vice
// versa), holding the same contrast ratio the light stop held against its
// own paired text (see the script's header comment for the full reasoning).
// Consumers that paired one of these fills with a fixed `trueWhite`/
// `trueBlack` label need that label switched to the self-inverting
// `white`/`black`, since the fill now flips right along with it.
//
// Re-run the script and paste its output here whenever a light-mode stop in
// `colors.ts` changes.
const darkColors = {
  gray: {
    100: "#41352c",
    300: "#493e38",
    500: "#655854",
    600: "#ac9d98",
    700: "#daccc8",
    900: "#fff7f9",
  },
  red: {
    100: "#43342b",
    300: "#593833",
    500: "#a13f38",
    600: "#f2887c",
    700: "#ffc8bc",
    900: "#ffe8e5",
  },
  // ---------------------------------------------------------------------------
  // The six brand ramps' 100-900 scales (see `colors.ts`'s `rampScaleStops`),
  // generated by `scripts/generate-ramp-scale.mjs`. `100`/`200`/`300`/`400`/
  // `700` relate to the page background and flip. `500`/`600`/`800`/`900` are
  // fills that invert role rather than staying identical: a light fill built
  // for black text becomes a dark fill built for white text (500), and a
  // dark fill built for white text becomes a light fill built for black text
  // (600, 800, 900) — `600`/`800` no longer match the (never-mode-aware) raw
  // `gradientStops` mid/deep hex in dark mode as a result; see the script's
  // header comment. `50` (hibiscus only, provisional) is a bg-anchored wash
  // like `100`/`200`/`300`/`400` — see `colors.ts`'s note.
  // ---------------------------------------------------------------------------
  hibiscus: {
    50: "#302d2d",
    100: "#413134",
    200: "#4a3339",
    300: "#53363d",
    400: "#783c4b",
    500: "#983c57",
    600: "#e7839c",
    700: "#febfd4",
    800: "#ffc6db",
    900: "#fff9fc",
  },
  hotsauce: {
    100: "#362e2b",
    200: "#372e2b",
    300: "#41322c",
    400: "#623b2d",
    500: "#823d24",
    600: "#db7753",
    700: "#ffa88d",
    800: "#ffbba7",
    900: "#ffece7",
  },
  chilioil: {
    100: "#483634",
    200: "#523936",
    300: "#5c3b39",
    400: "#83423f",
    500: "#a54240",
    600: "#fc8b85",
    700: "#ffd0ce",
    800: "#fed4d3",
    900: "#fff9f9",
  },
  blackberry: {
    100: "#3f3232",
    200: "#473535",
    300: "#4f3838",
    400: "#6e4242",
    500: "#8b474a",
    600: "#d78c8d",
    700: "#febcdb",
    800: "#fdc6ed",
    900: "#fffafd",
  },
  figjam: {
    100: "#453841",
    200: "#4d3b48",
    300: "#553f4f",
    400: "#754869",
    500: "#904c7f",
    600: "#e196cd",
    700: "#edd4ff",
    800: "#e9dafe",
    900: "#fdfaff",
  },
  marmalade: {
    100: "#342f24",
    200: "#352e20",
    300: "#3b311e",
    400: "#533f12",
    500: "#634800",
    600: "#a78641",
    700: "#cfb17a",
    800: "#cdb282",
    900: "#fee7c2",
  },
} as const;

export default darkColors;
