import { createSystem, defaultConfig, defineConfig } from "@chakra-ui/react";

import { defaultFontSizes } from "../../utils";
import colors, { type GradientName, rampScaleStops } from "./colors";
import darkColors from "./darkColors";
import fonts from "./fonts";
import { buildGradientTokens } from "./gradients";
import { recipes, slotRecipes } from "./recipes";

// ---------------------------------------------------------------------------
// Helper: recursively convert a nested colour object into Chakra v3 token
// format where every leaf string becomes { value: "..." }.
// Non-string leaves (functions, arrays, objects that aren't colour scales)
// are skipped so that composite entries like `grad`, `modes`, `current`,
// `success`, and `failure` are not accidentally tokenised.
// ---------------------------------------------------------------------------
function toColorScale(obj: Record<string | number, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (typeof v === "string") {
      out[String(k)] = { value: v };
    } else if (v !== null && typeof v === "object" && !Array.isArray(v)) {
      const nested = toColorScale(v as Record<string | number, unknown>);
      if (Object.keys(nested).length > 0) {
        out[String(k)] = nested;
      }
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Colour tokens
// The full CodeDay palette overrides Chakra v3's built-in defaults so that
// references like `bg="red.700"` or `color="gray.1100"` resolve to our brand
// values rather than the Chakra defaults.
// ---------------------------------------------------------------------------
// `gray` and `red` are excluded here — they're mode-aware (see
// `darkModePaletteTokens` below) rather than flat, single-value tokens.
const PALETTE_KEYS = [
  "orange",
  "yellow",
  "green",
  "teal",
  "cyan",
  "blue",
  "indigo",
  "purple",
  "pink",
] as const;

const paletteTokens = Object.fromEntries(
  PALETTE_KEYS.map((key) => [key, toColorScale(colors[key] as Record<string | number, unknown>)]),
);

// ---------------------------------------------------------------------------
// Mode-aware palettes: `gray`/`red`'s stops, and each of the six brand
// ramps' 100-900 scale (`rampScaleStops` — see `colors.ts`), flip between
// light and dark values via Chakra's `_dark` semantic-token condition,
// instead of being one flat value used unchanged in both modes. The dark
// values come from `darkColors.ts` (generated by `scripts/generate-dark-
// scale.mjs` / `generate-ramp-scale.mjs`, an OKLCH contrast-ratio search —
// not hand-picked or a mechanical inversion of the light scale). Consumers
// keep writing plain token paths like `"gray.600"` or `"hibiscus.700"` (or,
// under a section that's set `colorPalette="hibiscus"`, `"colorPalette.700"`);
// nothing about how they're referenced changes.
// ---------------------------------------------------------------------------
const MODE_AWARE_PALETTES: Record<string, Record<string, string>> = {
  gray: colors.gray,
  red: colors.red,
  ...rampScaleStops,
};
const darkModePaletteTokens = Object.fromEntries(
  Object.entries(MODE_AWARE_PALETTES).map(([key, lightStops]) => [
    key,
    Object.fromEntries(
      Object.entries(lightStops).map(([stop, lightHex]) => [
        stop,
        {
          value: {
            base: lightHex,
            _dark: (darkColors as Record<string, Record<string, string>>)[key][stop],
          },
        },
      ]),
    ),
  ]),
);

// ---------------------------------------------------------------------------
// The six brand gradients: `<name>.gradient.full` / `.button` / etc (stop
// lists, angle stays at the call site) and `<name>.badgeGradient`. Nested
// under each ramp name (rather than a separate top-level `gradient.*`
// namespace) so Chakra's `colorPalette` prop can address them — a section
// wrapper sets `colorPalette="figjam"` once and every descendant recipe
// referencing `colorPalette.gradient.button` picks it up (the per-section
// primary fills). The ramp's discrete 100-900 swatches (including `600`/
// `800`, pinned to these same gradients' 62%/40% stops) live in
// `darkModePaletteTokens` above instead — they're mode-aware, these
// continuous gradients are not.
// ---------------------------------------------------------------------------
const gradientTokenSets = buildGradientTokens();
const rampColorTokens = Object.fromEntries(
  Object.entries(gradientTokenSets).map(
    ([name, { full, button, badgeGradient, criticalField, emptyState, rail, modal }]) => [
      name,
      {
        badgeGradient: { value: badgeGradient },
        gradient: {
          full: { value: full },
          button: { value: button },
          critical: { value: criticalField },
          emptyState: { value: emptyState },
          rail: { value: rail },
          modal: { value: modal },
        },
        // Fixed, non-inverting duplicate of this ramp's mode-aware 100-900
        // scale (`colorPalette.<stop>`, wired below via
        // `darkModePaletteTokens`) — for the rare case a component sits on a
        // ground that itself never changes with dark mode (e.g. inside a
        // `Wash`) and needs a palette swatch that won't flip out from under
        // it. Always the light-mode value, same rationale as `trueBlack`/
        // `trueWhite` below. Everywhere else, use the bare
        // `colorPalette.<stop>` scale, which is mode-aware on purpose.
        true: toColorScale(
          rampScaleStops[name as GradientName] as Record<string | number, unknown>,
        ),
      },
    ],
  ),
);

const colorTokens = {
  ...paletteTokens,
  ...rampColorTokens,

  // Scalar colours
  brand: { value: colors.brand as string },

  // Fixed, non-inverting ink/paper — for the rare case a color needs to stay
  // put across modes (a label on a gradient that itself never changes with
  // dark mode, text over a permanently-dark photo/video scrim). Everywhere
  // else, use `black`/`white` below, which flip on purpose.
  trueBlack: { value: colors.black as string },
  trueWhite: { value: colors.white as string },

  // Fixed, non-inverting duplicates of `gray`/`red`'s mode-aware 100-900
  // scale (wired below via `darkModePaletteTokens`) — same rationale as
  // `trueBlack`/`trueWhite` above and each ramp's own `<ramp>.true.*` above.
  // Always the light-mode value.
  gray: { true: toColorScale(colors.gray as Record<string | number, unknown>) },
  red: { true: toColorScale(colors.red as Record<string | number, unknown>) },

  // Alpha ramps (already defined locally in colors.ts as plain objects)
  blackAlpha: toColorScale(colors.blackAlpha as Record<string | number, unknown>),
  whiteAlpha: toColorScale(colors.whiteAlpha as Record<string | number, unknown>),
};

// ---------------------------------------------------------------------------
// Semantic tokens — colour-mode-aware aliases
//
// `current.*` mirrors the old v2 `theme.colors.modes.{light,dark}` pattern.
// They flip automatically between the `base` (light) and `_dark` values when
// next-themes adds the `.dark` class to <html>.
// ---------------------------------------------------------------------------
const semanticColorTokens = {
  ...darkModePaletteTokens,

  // `black`/`white` invert instead of staying flat: `black` is near-black ink
  // in light mode and near-white in dark mode (the page's actual foreground,
  // whichever mode it's in); `white` is the mirror, tracking the page's own
  // background. Anything that needs to stay a fixed ink/paper color
  // regardless of mode should use `trueBlack`/`trueWhite` instead (see
  // `colorTokens` above).
  black: {
    value: {
      base: colors.black as string,
      _dark: "{colors.whiteAlpha.900}",
    },
  },
  white: {
    value: {
      base: colors.white as string,
      _dark: "#292929",
    },
  },

  // Small marker-dot colors (status indicators sitting directly on the page,
  // no paired label) — `teal`/`gray` aren't mode-aware palettes, and even
  // where a stop is (gray.500), its dark-mode value is now solved as a fill
  // paired with a fixed label, not as a bare accent against the page's own
  // background, so it can't be reused here. Light-mode values match the
  // original teal.600/gray.500 exactly; only the dark side is new.
  status: {
    open: { value: { base: "{colors.teal.600}", _dark: "{colors.teal.500}" } },
    interest: { value: { base: "{colors.gray.500}", _dark: "#B8A7A1" } },
  },

  current: {
    // Backgrounds
    // gray.1100 is removed from the palette (step 5 of the palette migration) — the
    // dark-mode ground is hardcoded here at its old value rather than being
    // a palette stop; picking a new one is a separate decision.
    bg: { value: "{colors.white}" },
    background: { value: "{colors.white}" },

    // Foreground text
    text: { value: "{colors.black}" },
    // Alias used in a few legacy call-sites
    textColor: { value: "{colors.black}" },
    // Per the earlier palette audit: this held the OLD hardcoded muted-text
    // value (#717171) even after the semantic palette swap, so table
    // headers/form help text quietly drifted off the new gray.600
    // (#6F5F5A) — close enough to look fine, wrong enough to be a second
    // source of "muted gray" alongside the real one.
    textLight: {
      value: {
        base: "{colors.gray.600}",
        _dark: "{colors.whiteAlpha.600}",
      },
    },

    // Brand / primary
    primary: {
      value: {
        base: "{colors.brand}",
        _dark: "{colors.brand}",
      },
    },

    // Borders
    border: {
      value: {
        base: "{colors.gray.300}",
        _dark: "{colors.whiteAlpha.300}",
      },
    },
    borderColor: {
      value: {
        base: "{colors.gray.300}",
        _dark: "{colors.whiteAlpha.300}",
      },
    },

    // Placeholder text
    placeholder: {
      value: {
        base: "{colors.gray.600}",
        _dark: "{colors.whiteAlpha.400}",
      },
    },
  },
};

// ---------------------------------------------------------------------------
// Legacy theme object
// Kept for the handful of non-Chakra consumers that call useTheme() and
// access colours / fontSizes / radii directly (CognitoForm style generator,
// Html prose renderer, DataCollection icon sizing, etc.).
// ---------------------------------------------------------------------------
export const Theme: Record<string, any> = {
  colors,
  fonts,
  fontSizes: defaultFontSizes,
  cognito: {
    id: "7hYXr3TPxk6yIpJxjqVoFQ",
  },
  config: {
    initialColorMode: "system",
    useSystemColorMode: true,
  },
};

// ---------------------------------------------------------------------------
// Chakra v3 system
// ---------------------------------------------------------------------------
const config = defineConfig({
  theme: {
    // Custom keyframes referenced by name in component `animation` props.
    // Must be registered here, not declared inline in a component's own
    // `css` prop — Chakra v3 only emits a real `@keyframes` rule for names
    // it knows about via this theme config, so an ad hoc
    // `css={{ "@keyframes foo": {...} }}` silently produces no rule at all:
    // `animation-name` ends up pointing at a keyframes list that doesn't
    // exist, which still registers as a "running" Animation (its timeline
    // ticks normally) but animates nothing, since there's no effect to
    // interpolate.
    keyframes: {
      "skelly-load": {
        from: { backgroundPosition: "200% 0" },
        to: { backgroundPosition: "-200% 0" },
      },
    },

    tokens: {
      colors: colorTokens as any,

      // Restores the v2 `container.*` size namespace (removed in v3)
      sizes: {
        container: {
          sm: { value: "640px" },
          md: { value: "768px" },
          lg: { value: "1024px" },
          xl: { value: "1280px" },
        },
      },

      // Custom typefaces
      fonts: {
        body: { value: fonts.body },
        heading: { value: fonts.heading },
        mono: { value: fonts.mono },
        logo: { value: fonts.logo },
      },
    },

    semanticTokens: {
      colors: semanticColorTokens,
    },

    recipes,
    slotRecipes,
  },

  // ---------------------------------------------------------------------------
  // Global CSS
  // Body background and text colour track the active colour mode via the
  // semantic tokens above, so the page flips correctly when next-themes
  // toggles the `.dark` class on <html>.
  // ---------------------------------------------------------------------------
  globalCss: {
    body: {
      bg: "current.bg",
      color: "black",
      lineHeight: "1.6",
      fontFamily: "body",
      transition: "background-color 0.3s",
    },
  },
});

export default createSystem(defaultConfig, config);
