import { createSystem, defaultConfig, defineConfig } from "@chakra-ui/react";

import { defaultFontSizes } from "../../utils";
import colors, { type GradientName, rampScaleStops } from "./colors";
import darkColors from "./darkColors";
import fonts from "./fonts";
import { buildGradientTokens } from "./gradients";
import { recipes, slotRecipes } from "./recipes";

// ---------------------------------------------------------------------------
// Helper: recursively convert a nested colour object into Chakra v3 token
// format where every leaf string becomes { value: "..." }.
// Non-string leaves (functions, arrays, objects that aren't colour scales)
// are skipped so that composite entries like `grad`, `modes`, `current`,
// `success`, and `failure` are not accidentally tokenised.
// ---------------------------------------------------------------------------
function toColorScale(obj: Record<string | number, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (typeof v === "string") {
      out[String(k)] = { value: v };
    } else if (v !== null && typeof v === "object" && !Array.isArray(v)) {
      const nested = toColorScale(v as Record<string | number, unknown>);
      if (Object.keys(nested).length > 0) {
        out[String(k)] = nested;
      }
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Colour tokens
// The full CodeDay palette overrides Chakra v3's built-in defaults so that
// references like `bg="red.700"` or `color="gray.1100"` resolve to our brand
// values rather than the Chakra defaults.
// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------
// Mode-aware palettes: every semantic hue's stops (all eleven — `gray`/`red`
// plus the nine colour hues), and each of the six brand ramps' 100-900 scale
// (`rampScaleStops` — see `colors.ts`), flip between light and dark values
// via Chakra's `_dark` semantic-token condition, instead of being one flat
// value used unchanged in both modes. The dark values come from
// `darkColors.ts` (generated by `scripts/generate-dark-scale.mjs` /
// `generate-ramp-scale.mjs`, an OKLCH contrast-ratio search — not
// hand-picked or a mechanical inversion of the light scale). Consumers keep
// writing plain token paths like `"gray.600"` or `"hibiscus.700"` (or, under
// a section that's set `colorPalette="hibiscus"`, `"colorPalette.700"`);
// nothing about how they're referenced changes.
// ---------------------------------------------------------------------------
const SEMANTIC_HUES: Record<string, Record<string, string>> = {
  gray: colors.gray,
  red: colors.red,
  orange: colors.orange,
  yellow: colors.yellow,
  green: colors.green,
  teal: colors.teal,
  cyan: colors.cyan,
  blue: colors.blue,
  indigo: colors.indigo,
  purple: colors.purple,
  pink: colors.pink,
};
const MODE_AWARE_PALETTES: Record<string, Record<string, string>> = {
  ...SEMANTIC_HUES,
  ...rampScaleStops,
};
const darkModePaletteTokens = Object.fromEntries(
  Object.entries(MODE_AWARE_PALETTES).map(([key, lightStops]) => [
    key,
    Object.fromEntries(
      Object.entries(lightStops).map(([stop, lightHex]) => [
        stop,
        {
          value: {
            base: lightHex,
            _dark: (darkColors as Record<string, Record<string, string>>)[key][stop],
          },
        },
      ]),
    ),
  ]),
);

// ---------------------------------------------------------------------------
// The six brand gradients: `<name>.gradient.full` / `.button` / etc (stop
// lists, angle stays at the call site) and `<name>.badgeGradient`. Nested
// under each ramp name (rather than a separate top-level `gradient.*`
// namespace) so Chakra's `colorPalette` prop can address them — a section
// wrapper sets `colorPalette="figjam"` once and every descendant recipe
// referencing `colorPalette.gradient.button` picks it up (the per-section
// primary fills). The ramp's discrete 100-900 swatches (including `600`/
// `800`, pinned to these same gradients' 62%/40% stops) live in
// `darkModePaletteTokens` above instead — they're mode-aware, these
// continuous gradients are not.
// ---------------------------------------------------------------------------
const gradientTokenSets = buildGradientTokens();
const rampColorTokens = Object.fromEntries(
  Object.entries(gradientTokenSets).map(
    ([name, { full, button, badgeGradient, criticalField, emptyState, rail, modal }]) => [
      name,
      {
        badgeGradient: { value: badgeGradient },
        gradient: {
          full: { value: full },
          button: { value: button },
          critical: { value: criticalField },
          emptyState: { value: emptyState },
          rail: { value: rail },
          modal: { value: modal },
        },
        // Fixed, non-inverting duplicate of this ramp's mode-aware 100-900
        // scale (`colorPalette.<stop>`, wired below via
        // `darkModePaletteTokens`) — for the rare case a component sits on a
        // ground that itself never changes with dark mode (e.g. inside a
        // `Wash`) and needs a palette swatch that won't flip out from under
        // it. Always the light-mode value, same rationale as `trueBlack`/
        // `trueWhite` below. Everywhere else, use the bare
        // `colorPalette.<stop>` scale, which is mode-aware on purpose.
        true: toColorScale(
          rampScaleStops[name as GradientName] as Record<string | number, unknown>,
        ),
      },
    ],
  ),
);

const colorTokens = {
  ...rampColorTokens,

  // Scalar colours
  brand: { value: colors.brand as string },

  // Fixed, non-inverting ink/paper — for the rare case a color needs to stay
  // put across modes (a label on a gradient that itself never changes with
  // dark mode, text over a permanently-dark photo/video scrim). Everywhere
  // else, use `black`/`white` below, which flip on purpose.
  trueBlack: { value: colors.black as string },
  trueWhite: { value: colors.white as string },

  // Fixed, non-inverting duplicates of every semantic hue's mode-aware
  // 100-900 scale (wired below via `darkModePaletteTokens`) — same rationale
  // as `trueBlack`/`trueWhite` above and each ramp's own `<ramp>.true.*`
  // above. Always the light-mode value.
  ...Object.fromEntries(
    Object.entries(SEMANTIC_HUES).map(([key, stops]) => [
      key,
      { true: toColorScale(stops as Record<string | number, unknown>) },
    ]),
  ),

  // Alpha ramps (already defined locally in colors.ts as plain objects)
  blackAlpha: toColorScale(colors.blackAlpha as Record<string | number, unknown>),
  whiteAlpha: toColorScale(colors.whiteAlpha as Record<string | number, unknown>),
};

// ---------------------------------------------------------------------------
// Semantic tokens — colour-mode-aware aliases
//
// `current.*` mirrors the old v2 `theme.colors.modes.{light,dark}` pattern.
// They flip automatically between the `base` (light) and `_dark` values when
// next-themes adds the `.dark` class to <html>.
// ---------------------------------------------------------------------------
const semanticColorTokens = {
  ...darkModePaletteTokens,

  // `black`/`white` invert instead of staying flat: `black` is near-black ink
  // in light mode and near-white in dark mode (the page's actual foreground,
  // whichever mode it's in); `white` is the mirror, tracking the page's own
  // background. Anything that needs to stay a fixed ink/paper color
  // regardless of mode should use `trueBlack`/`trueWhite` instead (see
  // `colorTokens` above).
  black: {
    value: {
      base: colors.black as string,
      _dark: "{colors.whiteAlpha.900}",
    },
  },
  white: {
    value: {
      base: colors.white as string,
      _dark: "#1E1119",
    },
  },

  // Small marker-dot colors (status indicators sitting directly on the page,
  // no paired label) — `teal`/`gray` aren't mode-aware palettes, and even
  // where a stop is (gray.500), its dark-mode value is now solved as a fill
  // paired with a fixed label, not as a bare accent against the page's own
  // background, so it can't be reused here. Light-mode values match the
  // original teal.600/gray.500 exactly; only the dark side is new.
  status: {
    open: { value: { base: "{colors.teal.600}", _dark: "{colors.teal.500}" } },
    interest: { value: { base: "{colors.gray.500}", _dark: "#B8A7A1" } },
  },

  current: {
    // Backgrounds
    // gray.1100 is removed from the palette (step 5 of the palette migration) — the
    // dark-mode ground is hardcoded here at its old value rather than being
    // a palette stop; picking a new one is a separate decision.
    bg: { value: "{colors.white}" },
    background: { value: "{colors.white}" },

    // Foreground text
    text: { value: "{colors.black}" },
    // Alias used in a few legacy call-sites
    textColor: { value: "{colors.black}" },
    // Per the earlier palette audit: this held the OLD hardcoded muted-text
    // value (#717171) even after the semantic palette swap, so table
    // headers/form help text quietly drifted off the new gray.600
    // (#6F5F5A) — close enough to look fine, wrong enough to be a second
    // source of "muted gray" alongside the real one.
    textLight: {
      value: {
        base: "{colors.gray.600}",
        _dark: "{colors.whiteAlpha.600}",
      },
    },

    // Brand / primary
    primary: {
      value: {
        base: "{colors.brand}",
        _dark: "{colors.brand}",
      },
    },

    // Borders
    border: {
      value: {
        base: "{colors.gray.300}",
        _dark: "{colors.whiteAlpha.300}",
      },
    },
    borderColor: {
      value: {
        base: "{colors.gray.300}",
        _dark: "{colors.whiteAlpha.300}",
      },
    },

    // Placeholder text
    placeholder: {
      value: {
        base: "{colors.gray.600}",
        _dark: "{colors.whiteAlpha.400}",
      },
    },
  },

  // ---------------------------------------------------------------------------
  // Chakra's OWN built-in semantic tokens (`bg.*`/`fg.*`/`border.*` and the
  // per-hue `<hue>.fg/subtle/muted/emphasized/solid/focusRing/border/
  // contrast` groups shipped in `@chakra-ui/react`'s `defaultConfig`)
  // reference raw numbered stops like `gray.50`/`red.700`, expecting
  // Chakra's OWN native monotonic light-to-dark scale. Our semantic palette
  // repurposes those same stop numbers under a completely different,
  // role-based contract (`colors.ts`'s "stop contract") — now that every
  // hue covers the full 50-900 range, Chakra's own defaults silently
  // resolve to the WRONG role. E.g. its `fg.DEFAULT` dark value references
  // `{colors.gray.50}` expecting a near-white, readable text colour, but
  // our `gray.50` is a bg-anchored wash deliberately close to the page
  // background. Anything that falls through to a Chakra-default recipe
  // instead of one of our own fully-specified recipes (`Atom/Card`'s
  // `body`/`root` slots, for instance, which never set their own `color`)
  // silently inherits an unreadable colour as a result — see the Card dark
  // mode contrast bug this was written to fix.
  //
  // `createSystem(defaultConfig, config)` deep-merges configs (see
  // `styled-system/merge-config.js`'s recursive `mergeWith`), so a plain
  // `{ value: "..." }` string here cleanly *replaces* Chakra's own
  // `{ value: { _light, _dark } }` object at the same key (the merge falls
  // through to `Object.assign` once one side isn't an object) rather than
  // partially merging alongside it. Every value below is a single
  // reference into our own already mode-aware tokens, so it resolves
  // correctly in both modes without needing an explicit `_light`/`_dark`
  // split here.
  // ---------------------------------------------------------------------------
  bg: {
    DEFAULT: { value: "{colors.white}" },
    subtle: { value: "{colors.gray.50}" },
    muted: { value: "{colors.gray.100}" },
    emphasized: { value: "{colors.gray.200}" },
    inverted: { value: "{colors.black}" },
    panel: { value: "{colors.white}" },
    error: { value: "{colors.red.100}" },
    warning: { value: "{colors.orange.100}" },
    success: { value: "{colors.green.100}" },
    info: { value: "{colors.blue.100}" },
  },
  fg: {
    DEFAULT: { value: "{colors.black}" },
    muted: { value: "{colors.gray.600}" },
    subtle: { value: "{colors.gray.500}" },
    inverted: { value: "{colors.white}" },
    // `.700` is our "on-wash / on-page text" stop (see `colors.ts`'s stop
    // contract) — purpose-built for exactly this "readable status text on
    // the page background" role.
    error: { value: "{colors.red.700}" },
    warning: { value: "{colors.orange.700}" },
    success: { value: "{colors.green.700}" },
    info: { value: "{colors.blue.700}" },
  },
  // `border.*` can't reuse a single `{colors.gray.NNN}` reference the way
  // `bg`/`fg` do above — `gray`'s own dark counterparts are tuned for their
  // wash/fill roles, not for a border line surviving on the dark page
  // background, which is what `current.border` (whiteAlpha-based) already
  // solves correctly. Same `_light`/`_dark` pairing as `current.border`.
  border: {
    DEFAULT: { value: { _light: "{colors.gray.300}", _dark: "{colors.whiteAlpha.300}" } },
    muted: { value: { _light: "{colors.gray.100}", _dark: "{colors.whiteAlpha.100}" } },
    subtle: { value: { _light: "{colors.gray.50}", _dark: "{colors.whiteAlpha.50}" } },
    emphasized: { value: { _light: "{colors.gray.400}", _dark: "{colors.whiteAlpha.400}" } },
    inverted: { value: { _light: "{colors.whiteAlpha.400}", _dark: "{colors.gray.300}" } },
    error: { value: "{colors.red.500}" },
    warning: { value: "{colors.orange.500}" },
    success: { value: "{colors.green.500}" },
    info: { value: "{colors.blue.500}" },
  },

  // Per-family groups (`colorPalette.fg`/`.subtle`/etc, and the bare
  // `gray.fg`/`red.solid`/etc paths Chakra's own defaults use directly) —
  // for every family, the eleven semantic hues *and* the six brand ramps
  // alike, so a `colorPalette` can be set to any of the seventeen and
  // behave identically. (For the ten hues Chakra also ships, this doubles
  // as the override of Chakra's own stock group, which references its own
  // stop roles.) One consistent formula across all of them: `.600` is
  // every family's "dark fill / white text" stop (verified by
  // `colors.test.ts` for hues and ramps alike) — it also
  // role-inverts to a *light* fill in dark mode, so `contrast`'s text must
  // invert right along with it, which is exactly what our own
  // self-inverting `white` token already does (light mode: white; dark
  // mode: `#1E1119`, i.e. dark-ish — the correct polarity for text sitting
  // on a fill that just flipped from dark-under-white-text to
  // light-under-black-text).
  //
  // Spread *into* each hue's existing mode-aware `50`-`900` stops (registered
  // via `darkModePaletteTokens` above) rather than as a fresh object: this is
  // a top-level spread onto the same `gray`/`red`/... key, so a bare object
  // literal here would replace the numbered stops wholesale, and those hues
  // would silently fall back to Chakra's own flat stock scale in both modes.
  ...Object.fromEntries(
    Object.keys(MODE_AWARE_PALETTES).map((hue) => [
      hue,
      {
        ...darkModePaletteTokens[hue],
        contrast: { value: "{colors.white}" },
        fg: { value: `{colors.${hue}.700}` },
        subtle: { value: `{colors.${hue}.100}` },
        muted: { value: `{colors.${hue}.200}` },
        emphasized: { value: `{colors.${hue}.300}` },
        solid: { value: `{colors.${hue}.600}` },
        focusRing: { value: `{colors.${hue}.500}` },
        border: { value: `{colors.${hue}.500}` },
      },
    ]),
  ),
};

// ---------------------------------------------------------------------------
// Legacy theme object
// Kept for the handful of non-Chakra consumers that call useTheme() and
// access colours / fontSizes / radii directly (CognitoForm style generator,
// Html prose renderer, DataCollection icon sizing, etc.).
// ---------------------------------------------------------------------------
export const Theme: Record<string, any> = {
  colors,
  fonts,
  fontSizes: defaultFontSizes,
  cognito: {
    id: "7hYXr3TPxk6yIpJxjqVoFQ",
  },
  config: {
    initialColorMode: "system",
    useSystemColorMode: true,
  },
};

// ---------------------------------------------------------------------------
// Chakra v3 system
// ---------------------------------------------------------------------------
const config = defineConfig({
  theme: {
    // Custom keyframes referenced by name in component `animation` props.
    // Must be registered here, not declared inline in a component's own
    // `css` prop — Chakra v3 only emits a real `@keyframes` rule for names
    // it knows about via this theme config, so an ad hoc
    // `css={{ "@keyframes foo": {...} }}` silently produces no rule at all:
    // `animation-name` ends up pointing at a keyframes list that doesn't
    // exist, which still registers as a "running" Animation (its timeline
    // ticks normally) but animates nothing, since there's no effect to
    // interpolate.
    keyframes: {
      "skelly-load": {
        from: { backgroundPosition: "200% 0" },
        to: { backgroundPosition: "-200% 0" },
      },
    },

    tokens: {
      colors: colorTokens as any,

      // Restores the v2 `container.*` size namespace (removed in v3)
      sizes: {
        container: {
          sm: { value: "640px" },
          md: { value: "768px" },
          lg: { value: "1024px" },
          xl: { value: "1280px" },
        },
      },

      // Custom typefaces
      fonts: {
        body: { value: fonts.body },
        heading: { value: fonts.heading },
        mono: { value: fonts.mono },
        logo: { value: fonts.logo },
      },
    },

    semanticTokens: {
      colors: semanticColorTokens,
    },

    recipes,
    slotRecipes,
  },

  // ---------------------------------------------------------------------------
  // Global CSS
  // Body background and text colour track the active colour mode via the
  // semantic tokens above, so the page flips correctly when next-themes
  // toggles the `.dark` class on <html>.
  // ---------------------------------------------------------------------------
  globalCss: {
    html: {
      bg: "current.bg",
    },
    body: {
      bg: "current.bg",
      color: "black",
      lineHeight: "1.6",
      fontFamily: "body",
      transition: "background-color 0.3s",
    },
  },
});

// ---------------------------------------------------------------------------
// Chakra's stock hue scales carry an extra `950` stop. Our stop contract is
// `50`-`900` for every family, and nothing of ours defines or references a
// `950` — but a base token survives the config merge untouched, so without
// this it leaks through as a flat, off-palette, non-mode-aware stop on
// exactly the ten families Chakra happens to ship (and on none of the other
// seven). Dropped here so every family exposes the same stops.
// ---------------------------------------------------------------------------
const stockColors = (defaultConfig.theme?.tokens?.colors ?? {}) as Record<string, unknown>;
const stockColorsWithout950 = Object.fromEntries(
  Object.entries(stockColors).map(([hue, scale]) => {
    if (!(hue in SEMANTIC_HUES) || typeof scale !== "object" || scale === null) {
      return [hue, scale];
    }
    const trimmed: Record<string, unknown> = { ...scale };
    delete trimmed[950];
    return [hue, trimmed];
  }),
) as typeof stockColors;

export default createSystem(
  {
    ...defaultConfig,
    theme: {
      ...defaultConfig.theme,
      tokens: { ...defaultConfig.theme?.tokens, colors: stockColorsWithout950 },
    },
  } as typeof defaultConfig,
  config,
);
